work/djangoWeb/courtDragProject/courtDragProject/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from home import views
from django.conf import settings

urlpatterns = patterns('',
    # Examples:
    #url(r'^$', 'courtDragProject.views.home', name='home'),
#   url(r'^$', 'courtDragProject.home.views.index'),
    url(r'^$', views.index, name = 'index'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
#    url(r'^home/', include('home')),
    url(r'^home/', include('home.urls', namespace="home")),
    
)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += patterns('',
        url(r'^__debug__/', include(debug_toolbar.urls)),
    )

work/djangoWeb/courtDragProject/home/urls.py
from django.conf.urls import patterns, include, url
#from django.contrib import admin
from home import views


urlpatterns = patterns('',
    # Examples:
    #url(r'^$', 'courtDragProject.views.home', name='home'),
#   url(r'^$', 'courtDragProject.home.views.index'),
    url(r'^search', views.search, name = 'search'),
    # url(r'^blog/', include('blog.urls')),
    url(r'^download/(.+)$',views.download,name = 'download'),
    url(r'batchDownload$',views.batchDownload,name='batchDownload'),
#    url(r'^admin/', include(admin.site.urls)),
#    url(r'^home/', include('home')),
#    url(r'^home/', include('home.urls', namespace="home)),
    
)

work/djangoWeb/courtDragProject/home/models.py
# -*- coding: utf-8 -*- 
from django.db import models

#class Pdf(models.Model):
#    id = models.AutoField(primary_key = True) #主键
#    keyWord = models.CharField('关键字:',max_length = 100,help_text = '最多输入100个关键字') #关键字
#    caseCode = models.CharField('案  号:',max_length = 100,help_text = '最多输入100个关键字') #案号
#    wenshuanyou = models.CharField('案由:',max_length = 100,help_text = '最多输入100个关键字') #案由
#    anjianleixing = models.CharField('案件类型:',max_length = 20)
#    docsourcename = models.CharField('文书类型:', max_length =20)
#    court = models.CharField('审理法院',max_length = 100,help_text = '最多输入100个关键字') #审理法院
#    beginDate = models.DateField('裁判时间：从')
#    endDate = models.DateField('到')
       
#    def __str__(self):
#        return "%s, %s, %s, %s, %s, %s, %s, %s"%(self.keyWord,self.caseCode,self.wenshuanyou,self.anjianleixing,self.docsourcename,self.court,self.beginDate,self.endDate)

#    class Admin:
 #       list_display = ("关键字")#,"caseCode","wenshuanyou","anjianleixing","docsourcename","court","beginDate","endDate")
  #      search_field = ("关键字")


# Create your models here.

#创建关于树的两张表
#table 1
#class treeNode(models.Model):
#    nodeid = models.AutoField(primary_key = True) #主键
#    nodeValue = models.CharField('节点名:',max_length = 100,help_text = '最多输入50个字') #节点的名字

#    def __str__(self):
#        return "%s,%s"%(self.nodeid,self.nodeValue)

#class nodeRelation(models.Model):
#    ancestor = models.PositiveIntegerField('父节点:',help_text = '请输入正整数')
#    descendant = models.PositiveIntegerField('子节点:',help_text = '请输入正整数')
#    depth = models.PositiveIntegerField('节点深度:',help_text = '请输入正整数')

#    def __str__(self):
#        return "%d,%d"%(self.ancestor,self.descendant,self.depth)

#table 2

#table 自引用
class  Category(models.Model):
    name = models.CharField('级别名称：', max_length = 100, blank = False)
    slug = models.SlugField('简称：', db_index = True)
    parent = models.ForeignKey('self', null = True, blank = True)
        
    def __unicode__(self):
        return u'%s' % self.name

work/djangoWeb/courtDragProject/home/views.py
#!/usr/bin/env python
# -*- coding: utf-8 -*- 
from django.shortcuts import render
import sys
import logging
import urllib2
import urllib
import types
from pyquery import PyQuery as pq
from django.http import HttpResponse
from django.template import Context,loader

#from home.utils import MyHTMLParser

#from django.http import HttpResponse

# Create your views here.
# 使得 sys.getdefaultencoding() 的值为 'utf-8'  
reload(sys)                      # reload 才能调用 setdefaultencoding 方法  
sys.setdefaultencoding('utf-8')  # 设置 'utf-8'

domainName = "http://www.court.gov.cn/extension/search.htm?";
dictKV = {}#文件id 和 名字
requestUrls = []

def index(request):
    return render(request,'home/index.html')

def search(request):
    if request.method =='GET':
        strKeyWord = request.GET.get("keyWord")
        strCaseCode = request.GET.get("caseCode")
        strWenshuanyou = request.GET.get("wenshuanyou")
        strAnjianleixing = request.GET.get("anjianleixing")
        strDocSourceName = request.GET.get("docsourcename")
        strCourt = request.GET.get("court")
        strBeginDate = request.GET.get("beginDate")
        strEndDate = request.GET.get("endDate")
        strPage = request.GET.get("page")
        logging.debug(strPage)
        #debug infomation
        logging.debug("strKeyWord is %s" % strKeyWord)
        logging.debug("strCaseCode is %s" % strCaseCode)
        logging.debug("strWenshuanyou is %s" % strWenshuanyou)
        logging.debug("strAnjianleixing is %s" % strAnjianleixing)
        logging.debug("strDocSourceName is %s" % strDocSourceName)
        logging.debug("strCourt is %s" % strCourt)
        logging.debug("strBeginDate is %s" % strBeginDate)
        logging.debug("strEndDate is %s" % strEndDate)
        logging.debug("strPage is %s" % strPage)

#        logging.debug("domain name is %s" % domainName)
        strReq = domainName
#        if strKeyWord!=None and strKeyWord!="":
        strReq = "%skeyword=%s"%(strReq,strKeyWord)
        logging.debug(strKeyWord)
#        elif strCaseCode!=None and strCaseCode!="":
        strReq = "%s&caseCode=%s"%(strReq,strCaseCode)
#        elif strWenshuanyou!=None and strWenshuanyou!="":
        strReq = "%s&wenshuanyou=%s"%(strReq,strWenshuanyou)
#        elif strAnjianleixing!=None and strAnjianleixing!="":
        strReq = "%s&anjianleixing=%s"%(strReq,strAnjianleixing)
#        elif strDocSourceName !=None and strDocSourceName!="":
        strReq = "%s&docsourcename=%s"%(strReq,strDocSourceName)
#        elif strCourt!=None and strCourt!="":
        strReq = "%s&court=%s"%(strReq,strCourt)
#        elif strBeginDate!=None and strBeginDate!="":
        strReq = "%s&beginDate=%s"%(strReq,strBeginDate)
#        elif strEndDate!=None and strEndDate!="":
        strReq = "%s&endDate=%s"%(strReq,strEndDate)
#        elif strPage!=None and strPage!="":
#        index = strReq.find("&page")
#        logging.debug(strPage)
#        logging.debug(index)
#        if strReq.find("&page"):
#            index = strReq.find("&page")
#            strReq = strReq[0:index]
        if strPage!=None:
            strReq = "%s&adv=1&orderby=&order=&page=%s"%(strReq,strPage)
        
                            
        
#        domainName+"keyword="+strKeyWord+"&caseCode"+strCaseCode+"&wenshuanyou"+strWenshuanyou+"&anjianleixing"+strAnjianleixing+"&docsourcename="+strDocSourceName+"&court="+strCourt+"&beginDate="+strBeginDate+"&endDate="+strEndDate
#        strReq = urllib.urlencode(strReq)
        req = urllib2.Request(strReq)
        logging.debug("returnUrl %s" % strReq)        
        try:
            response = urllib2.urlopen(req,timeout=30)
            the_page = response.read()
            #file_object = open('/Users/corrin/Desktop/test.txt')
            #content = file_object.read()
            content = the_page

            # myParser = MyHTMLParser()
            # myParser.feed(content)
            # filterStr = myParser.getValue

            #.getTableBodyAndPage(content,"//table[@class='tablestyle']")

            pqDoc = pq(content)
            tbodyDoc = pqDoc('table .tablestyle')
            nextTable = tbodyDoc.next().outerHtml()

            trs = tbodyDoc('tr:gt(0)')
#            logging.debug("trs type is %s"%type(trs))
            trsFinal = ''
            dictKV.clear() #先清空,用于全部下载
            for tr in trs:
                requestUrl = pq(tr)('a').attr['href']
#               
                start = requestUrl.index('_')+1
                end = requestUrl.rindex('.')
                key = requestUrl[start:end]
                value = pq(tr)('a').attr('title')

                dictKV[key] = value
#                requestUrl = "http://www.court.gov.cn/downloadPdf/Download?docId=%s"%requestUrl[start:end]
                requestUrl = "/home/download/%s"%urllib.urlencode({key:value})

                requestUrls.append(requestUrl)
#                strContent = str("%s%s"%("<td><input type='checkbox' /></td>",pq(tr).html()))
                strContent = str("%s"%pq(tr).html())
                trsFinal += "<tr>%s<td align='center'><a href = '%s'>下载</a></td></tr>"%(strContent,requestUrl)
#                logging.debug("return %s" % pq(tr).html())
            #下一个table的 html 内容
            trsFinal+=nextTable
            context = {'htmlContent':trsFinal}
            return render(request,'home/result.html',context)
            #return render(request,'home/result.html',Context({'htmlContent':trsFinal}))
            

        except Exception as ex:
            print ex
            return render(request,'home/timeout.html')
#            print e.read()
#单个pdf文件下载
def download(request,param):
    try:
        fixedUrl = "http://www.court.gov.cn/downloadPdf/Download?docId="
        paramArray = param.split('=')
        url = "%s%s"%(fixedUrl,paramArray[0])
        filePathName = "%s.pdf"%paramArray[1]
        urllib.urlretrieve(url,filePathName)
        return HttpResponse("<script>alert('%s文件已下载');history.go(-1);</script>"%filePathName)
    except:
        return HttpResponse("<script>alert('服务器出现错误，请重试！');history.go(-1);</script>")

#批量下载pdf文件
def batchDownload(request):
    fixedUrl = "http://www.court.gov.cn/downloadPdf/Download?docId="
    try:
        logging.debug(dictKV)
        if dictKV != None and len(dictKV) >0 :
            for key,value in dictKV.items():
                url = "%s%s"%(fixedUrl,key)
                filePathName = "%s.pdf"%value
                urllib.urlretrieve(url,filePathName)
        return HttpResponse("<script type='text/javascript'>alert('全部文件已下载');</script>")
    except:
        return HttpResponse("<script>alert('下载过程中出现错误！');history.go(-1);</script>")


    

#    f = urllib2.urlopen(url)
#    data = f.read()
#    logging.debug(data)
#    with open ("a.pdf","wb") as code:
#        code.write(data)
#    return HttpResponse(None)
#    urllib.urlretrieve(url,"/aa.pdf")#"%s.pdf" % paramArray[1])


    

#    return HttpResponse("Hello,world!")

work/djangoWeb/courtDragProject/home/templates/home/index.html
{% load staticfiles %}
<html>
  <head>
    <meta http-equiv="content-type" content="text/html; charset=utf-8"/>
    <title>pdf 文档下载程序</title>
  <!--[if IE]>
           <link rel="stylesheet" href="url" type="text/css" media="screen" />
           <![endif]-->
  <link rel="stylesheet" href="{% static 'home/style.css' %}" type="text/css" media="screen" />
  <link rel="stylesheet" type="text/css" href="{% static 'home/jquery.datetimepicker.css' %}"/>
  <script type="text/javascript" src="{% static 'home/jquery.js' %}"></script>
  <script type="text/javascript" src="{% static 'home/jquery.datetimepicker.js' %}"></script>
  </head>
  <body>
    <div id="wrap" >
      <div id="top"></div>
      <div id="indexTitle">中国裁判文书网pdf文档批量下载(如有法律纠纷，与开发者［或机构］无关)</div>
      
      <form action="{% url 'home:search' %}" method = "get">

        
        <br/><br/><br/>
        
      &nbsp; &nbsp; &nbsp; &nbsp;  <label>关键字：</label>
        <input type="text" name="keyWord" value="" maxlength="100" size="100"></input><br/><br/>
      &nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp; &nbsp;<label>案号：</label>
        <input type="text" name="caseCode" value="" maxlength="100" size="40" ></input>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
        <label>案由:</label>
        <input type="text" name="wenshuanyou" value="" maxlength="100" size="40" ></input><br/><br/>
        &nbsp; &nbsp; &nbsp; &nbsp; <label>案件类型：</label>
        <select name="anjianleixing">
          <option></option>
          <option value="民事案件">民事案件</option>
          <option>刑事案件</option>
          <option>行政案件</option>
          <option>知识产权</option>
          <option>赔偿案件</option>
          <option>执行案件</option>
        </select>
        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
        <label>文书类型：</label>
        <select name="docsourcename">
          <option></option>
          <option value="刑事裁定书">刑事裁定书</option><option>刑事判决书</option><option>刑事决定书</option>
          <option>民事裁定书</option><option>民事判决书</option><option>民事决定书</option>
          <option>行政裁定书</option><option>行政判决书</option><option>行政决定书</option>
          <option>国家赔偿裁定书</option><option>国家赔偿判决书</option><option>国家赔偿决定书</option>
          <option>执行判决书</option><option>执行决定书</option><option>执行裁定书</option>
          <option>通知书</option>
        </select><br/><br/>
        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<label>审理法院：</label>
        <input type="text" name="court" value="" maxlength="100" size="30" ></input>
        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<label>审判时间：</label>从<input id="beginDate" type="text" name="beginDate" value="2014-01-01" size="20" />
        <label>到：</label><input id="endDate" type="text" name="endDate" size="20" value="" /><br/><br/>
        <input id="btnSearch" type="submit"  value="搜索" />
      </form>
    </div>
    <script type="text/javascript">
      $(document).ready(function(){
      var date = new Date();
      var month = date.getMonth()+1;
      var day = date.getDate();
      var today = date.getFullYear()+'-'+
                  (month<10?'0':'')+month+'-'+
                  (day<10?'0':'')+day;
      $("#endDate").attr('value',today);
      })
      
      
    $('#beginDate').datetimepicker({
     	lang:'ch',
     	timepicker:false,
     	format:'Y-m-d',
     	formatDate:'Y-m-d'
    });
    $('#endDate').datetimepicker({
     	lang:'ch',
     	timepicker:false,
     	format:'Y-m-d',
        formatDate:'Y-m-d'
    });
    </script>
  </body>
</html>

work/djangoWeb/courtDragProject/home/templates/home/result.html
{% load staticfiles%}
<html>
  <head>
    <meta http-equiv="content-type" content="text/html; charset=utf-8"/>
    <link rel="stylesheet" href="{% static 'home/style.css' %}" type="text/css" media="screen" />
    <script type="text/javascript" src="{% static 'home/jquery-1.11.2.min.js' %}"></script>
    <title>文档搜索列表</title>
    <script type="text/javascript">
      $(document).ready(function(){
          $('#downloadAll').click(function(){
              $.get('batchDownload')
          })
      })     
    </script>
  </head>
  <body>
    <div id="wrap" >
      <div id="top"></div>
      <div id="resultTitle">搜索结果页（如有法律纠纷，与开发者［或机构无关］）：</div>
      <!--<input type="button" style="float:left;margin-left:750px" id="downloadSelect" name="downloadSelect" value="下载选中" />-->
      <input type="button" style="float:right;margin-right:20px" id="downloadAll" name="downloadAll" value="全部下载" />
      <table class="tablestyle" cellspacing="1" cellpadding="0" align="center">
              <tbody>
                <tr>
<!--                  <th width="15"><input type="checkbox" id="checkBoxAll" /></th>-->
                  <th width="40">序号</th>
                  <th width="140" onclick="setOrder('court')">审理法院&nbsp;<span id="courtarrow" style="font-weight: normal;"></span></th>
                  <th width="420" onclick="setOrder('doctitle')">标题&nbsp;<span id="doctitlearrow" style="font-weight: normal;"></span></th>
                  <th width="190" style="cursor: pointer" onclick="setOrder('wenshuanhao')">案号&nbsp;<span id="wenshuanhaoarrow" style="font-weight: normal;"></span></th>
                  <th width="90" onclick="setOrder('wenshuriqi')">裁判日期 &nbsp;<span id="wenshuriqiarrow" style="font-weight: normal;"></span></th>
                  <th width="50">操作</th>
                </tr>
                {%if htmlContent%}
                {%autoescape off%}
                {{htmlContent}}
                {%endautoescape%}
                {%endif%}
                
              </tbody>
      </table>
      
    </div>
  </body>
</html>

work/djangoWeb/courtDragProject/home/templates/home/timeout.html
<html>
  <head>
    <meta http-equiv="refresh" content="3;url=javascript:window.history.go(-1);">
  </head>
  <body>
    <div>网络访问超时，3秒后，返回<a href="javascript:history.back(-1);">上一页</a></div>
    <SCRIPT language=javascript>
      function go()
      {
          window.history.go(-1);
      }
      setTimeout("go()",3000);
</SCRIPT>
  </body>
</html>